src/Entity/Property.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify;
#use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity; #ajouté pour la validation
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PropertyRepository")
 * @UniqueEntity("title")
 * @Vich\Uploadable()
 */
class Property
{
    #@Vich\Uploadable() ajouter pour le upload de l'image
    #@UniqueEntity rend une nouvelle
    #declaration de la constante pour la propriété chauffage
    const HEAT = [
      0 => 'Electrique',
      1 => 'gaz',
      2 => 'bois'
    ];
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;
    /**
     * @var string|null
     * @ORM\Column(type="string", length=255)
     */
    private $filename;

    /**
     * @var File|null
     * @Assert\Image(
     *     mimeTypes="image/jpeg"
     * )
     * @Vich\UploadableField(mapping="property_image", fileNameProperty="filename")
     */
    private $imageFile;

    /**
     * @Assert\Length(min=5,max=255)
     * @ORM\Column(type="string", length=255)
     */
    private $title;

   
    
    /**
     * @ORM\Column(type="integer")
     * @Assert\Range(min=10, max=400)
     */
    private $surface;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $bedrooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $floor;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @ORM\Column(type="integer")
     */
    private $heat;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address;

    /**
     * @Assert\Regex("/^[0-9]{5}$/")
     * @ORM\Column(type="string", length=255)
     */
    private $postal_code;



    /**
     * @ORM\Column(type="boolean",options={"default": false})
     */
    private $sold = false;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Option", inversedBy="properties")
     */
    private $options;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    #création d'un constructeur avec paramètre et initialisation de la date

    public function __construct()
    {
        $this->created_at = new \DateTime();
        $this->options = new ArrayCollection();
    }

    #cette fonction est ajouté pour le csrf
    #public function configureOptions(OptionsResolver $resolver)
    #{
     #   $resolver->setDefaults([
      #      'data_class'      => Property::class,
       #     // enable/disable CSRF protection for this form
        #    'csrf_protection' => true,
         #   // the name of the hidden HTML field that stores the token
          #  'csrf_field_name' => '_token',
           # // an arbitrary string used to generate the value of the token
            #// using a different string for each form improves its security
            #'csrf_token_id'   => 'id',
        #]);
    #}


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    #ajout de slugify pour la convertion des chaines de caractère

    public function getSlug(): string {
        return (new Slugify())->slugify($this->title);
    }



    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    public function getBedrooms(): ?int
    {
        return $this->bedrooms;
    }

    public function setBedrooms(int $bedrooms): self
    {
        $this->bedrooms = $bedrooms;

        return $this;
    }

    public function getFloor(): ?int
    {
        return $this->floor;
    }

    public function setFloor(int $floor): self
    {
        $this->floor = $floor;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }
#une fonction qui se charge de formater le prix
    public function getFormattedPrice(): string
    {
       return number_format($this->price, 0,'',' ');
    }
    public function getHeat(): ?int
    {
        return $this->heat;
    }

    public function setHeat(int $heat): self
    {
        $this->heat = $heat;

        return $this;
    }

    #renvoi une chaine de caractère correspondante au numero de chauffage
    public function  getHeatType() :string
    {
        return self::HEAT[$this->heat];
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getSold(): ?bool
    {
        return $this->sold;
    }

    public function setSold(bool $sold): self
    {
        $this->sold = $sold;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return Collection|Option[]
     */
    public function getOptions(): Collection
    {
        return $this->options;
    }

    public function addOption(Option $option): self
    {
        if (!$this->options->contains($option)) {
            $this->options[] = $option;
            $option->addProperty($this);
        }

        return $this;
    }

    public function removeOption(Option $option): self
    {
        if ($this->options->contains($option)) {
            $this->options->removeElement($option);
            $option->removeProperty($this);
        }

        return $this;
    }

    /**
     * @return string|null
     */
    public function getFilename(): ?string
    {
        return $this->filename;
    }

    /**
     * @param string|null $filename
     * @return Property
     */
    public function setFilename(?string $filename): Property
    {
        $this->filename = $filename;
        return $this;
    }

    /**
     * @return File|null
     */
    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    /**
     * @param File|null $imageFile
     * @return Property
     */
    public function setImageFile(?File $imageFile): Property
    {
        $this->imageFile = $imageFile;
        if ($this->imageFile instanceof UploadedFile){
            $this->updated_at = new \DateTime('now');
        }
        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

}

src/Form/PropertyType.php
<?php

namespace App\Form;

use App\Entity\Option;
use App\Entity\Property;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;


class PropertyType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('description')
            ->add('surface')
            ->add('rooms')
            ->add('bedrooms')
            ->add('floor')
            ->add('price')
            ->add('heat', ChoiceType::class, [
                'choices' => $this->getChoices()
            ]) #l'ajout de choiceType permet de rendre un champ select;  'choices' => Property::HEAT: affiche la cle et non la valeur; $this->getChoices():retourne la valeur equivalent a la clé
            ->add('options', EntityType::class, [
               'class'   => Option::class,
                'required' => false,
                'choice_label' => 'name',
                'multiple' => true
            ])
            ->add('imageFile', FileType::class, [
                'required' => false
            ])
            ->add('city')
            ->add('address')
            ->add('postal_code')
            ->add('sold')
           # ->add('created_at') mettre ce champs en commentaire permet de refuser à l'utilisateur d'entrer lui même la date du jour

        ;
    }
#configureOptions permet de definir les differentes options du formulaire de manière globale
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Property::class,
            #la ligne suivante permet dopérer les changements sur les champs du formulaire
            'translation_domain' => 'forms'
        ]);
    }

    private function getChoices()
    {
       $choices = Property::HEAT; #recupere tout les options de la constante
        $output = [];
        #cette boucle retourne une valeur par rapport aux clés
        foreach ($choices as $k => $v){
           $output[$v] = $k;
        }
        return $output;
    }
}

src/Controller/PropertyController.php
<?php

#toujours commencer par mentionner le namespace
namespace App\Controller;

use App\Entity\Contact;
use App\Entity\Property;
use App\Entity\PropertySearch;
use App\Form\ContactType;
use App\Form\PropertySearchType;
use App\Notification\ContactNotification;
use App\Repository\PropertyRepository;
use Doctrine\Common\Persistence\ObjectManager;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class PropertyController extends AbstractController {


#<!--
#le bloc qui suit doit se placer dans la fonction index
    #ppremier methode d'insertion dans le code en dur hahahah

    #après avoir généré les entités on doit faire toujours cette action
    # $property = new Property();
    #$property->setTitle('Mon premier bien')
    #        ->setPrice(200000)
    #       ->setRooms(4)
    #      ->setBedrooms(3)
    #     ->setDescription('une petite description')
    #   ->setSurface(60)
    #  ->setFloor(4)
    # ->setHeat(1)
    #->setCity('Montpellier')
    #->setAddress('15 rue Boulevard du 20 mai')
    #->setPostalCode('34000');
    #une fois les données envoyées on fais la persistance et envoi a la bd
    #$em = $this->getDoctrine()->getManager();
    #$em->persist($property); #persistance de l'entité
    #$em->flush(); #permet de porter les données dans em vers la bd

    #recupere la données enrégistrée 1ere methode
    # $repository = $this->getDoctrine()->getRepository(Property::class); #instanciation du repository
    #dump($repository); #voir ce que ça retourne
    #$property = $this->repository->findAllVisible();
    #dump($property); affiche sous le terminal la variable
    # $property[0]->setSold(false); modifie la valeur du solde avant ajout
    #$this->em->flush();#permet de faire la mise à jour
#-->

    #recupere la données enrégistrée 2eme methode
    #ajout du 2em paramètre pour les mises à jours
    /**
     * @var PropertyRepository
     */
    private $repository;
    public function __construct(PropertyRepository $repository, ObjectManager $em)
    {
        $this->repository = $repository;
        $this->em = $em;
    }
    /**
     * @Route("/biens", name="property.index",)
    * @return Response
     */
    public function index(PaginatorInterface $paginator, Request $request): Response
    {
        ##debut recherche
            $search = new PropertySearch();
            $form = $this->createForm(PropertySearchType::class, $search);
            $form -> handleRequest($request);
        ##fin recherche

        #recupération de tout les biens
        # $properties = $this->repository->findAllVisible();
        #recupération de tout les biens avec pagination
        $properties = $paginator->paginate($this->repository->findAllVisibleQuery($search),
            $request->query->getInt('page', 1),
            12
            );
        #ce return permet d'envoyer les données à la vue
        return $this->render('property/index.html.twig',[
            'current_menu' => 'properties',
            'properties' => $properties,
            'form' => $form->createView()
        ]);
    }
    # 'property' => $property, envoie du proprité à la vue
    # statut 301 redirection instantanée
    #$slug, $id utiliser premierement en paramètre pour retourner une page
    #$property = $this->repository->find($id); dans la même idée ajouter cette ligne
    #requirements indique à quoi doivent ressembler les differentes paramètres
    /**
     * @Route("/biens/{slug}-{id}", name="property.show", requirements={"slug": "[a-z0-9\-]*"})
     * @param Property $property
     * @return Response
     */
    public function show(Property $property, string $slug,
                       Request $request,ContactNotification $notification): Response
    {

        #verifie si le slug fonctionne
        if ($property->getSlug() !== $slug){
            #si ce n'est pas egale redirection vers une route
            #cet bloc de code est très important pour le référencement des url
           return  $this->redirectToRoute('property.show', [
                'id' => $property->getId(),
                'slug' => $property->getSlug()
            ],301);
        }

        ## debut block contact
        $contact = new Contact();
        $contact->setProperty($property);
        $form = $this->createForm(ContactType::class, $contact);
        $form->handleRequest($request);
        #verification de la soumition et de la validation de l'email
        if($form->isSubmitted() && $form->isValid()){
            #notifier le client
            $notification->notify($contact);
            $this->addFlash('success','Votre email a bien été envoyé');
            return  $this->redirectToRoute('property.show', [
                'id' => $property->getId(),
                'slug' => $property->getSlug()
            ]);
        }
        ##fin block contact

        return $this->render('property/show.html.twig',[
            'property'      => $property,
            'current_menu'  => 'properties',
            'form'          => $form->createView()

        ]);
    }
}

templates/property/_property.html.twig
<div class="card mb-4">
    {% if property.filename %}
        {#
        première méthode d'affichage déconseillé en cas de changement du repertoir d'image
        #}
        <img src="{{ vich_uploader_asset(property, 'imageFile') | imagine_filter('thumb') }}" alt="card-img-top" style="width: 100%; height: auto;">
        {% else %}
            <img src="{{ '/images/properties/empty.jpg' | imagine_filter('thumb') }}" alt="card-img-top" style="width: 100%; height: auto;">
    {% endif %}
    <div class="card-body">
        <h5 class="card-title">
            <a href="{{ path('property.show', {slug: property.slug, id: property.id}) }}">
                {{ property.title }}
            </a>
        </h5>
        <p class="card-text">{{ property.surface }} m² - {{ property.city  }} ({{ property.postalCode }})</p>
        <div class="text-primary" style="font-size: 2rem; font-weight: bold;">
            {{ property.formattedPrice }} FCFA
        </div>
    </div>
</div>

templates/property/index.html.twig
{% extends 'base.html.twig' %}

{% block title 'Voir tous nos biens' %}
{% block body %}
    <div class="jumbotron">
        <div class="container">
            {# syntaxe d'insertion des formulaire#}
            {{ form_start(form) }}
              <div class="form-row align-items-end">
                  <div class="col">
                      {{ form_row(form.minSurface) }}
                  </div>
                  <div class="col">
                      {{ form_row(form.maxPrice) }}
                  </div>
                  <div class="col">
                      {{ form_row(form.options) }}
                  </div>
                  <div class="col">
                     <div class="form-group">
                         <button class="btn btn-primary">Rechercher</button>
                     </div>
                  </div>
              </div>
            {{ form_end(form) }}
        </div>
    </div>
    <div class="container mt-4">
        <h1>Nos Biens</h1>

    <div class="row">
        {% for property in properties %}
            <div class="col-md-4">
                {% include 'property/_property.html.twig' %}
            </div>
        {% endfor %}
    </div>
        <div class="pagination">
            {{ knp_pagination_render(properties) }}
        </div>
    </div>
{% endblock %}

templates/property/show.html.twig
{%  extends 'base.html.twig' %}

{% block title property.title %}

{% block body %}
 <div class="container mt-4">
     {% for message in app.flashes('success') %}
         <div class="alert alert-success">
             {{ message }}
         </div>
     {% endfor %}

     {#vérifier si le form est valide et afficher le sms qui suit vars objet qui contient tout les données du formulaire#}

     {% if not form.vars.valid %}
         <div class="alert alert-danger">
             Veuillez bien  remplir les champs
         </div>
     {% endif %}
     <div class="row">
         <div class="col-md-8">
             {% if property.filename %}
                 {#
                 première méthode d'affichage déconseillé en cas de changement du repertoir d'image
                   <img src="{{ '/images/properties/empty.jpg' | imagine_filter('thumb') }}" alt="card-img-top" style="width: 100%; height: auto;">
                 #}
                 <img src="{{ vich_uploader_asset(property, 'imageFile') | imagine_filter('thumb') }}" alt="card-img-top" style=" width: 360px; height: 260px;">
             {% else %}
                 <img src="{{ '/images/properties/empty.jpg' | imagine_filter('thumb') }}" alt="card-img-top" style="width: 360px; height: 260px;">
             {% endif %}
         </div>
         <div class="col-md-4">
             <h1>{{ property.title }}</h1>
             <h2>{{ property.rooms }} pièces - {{ property.surface }} m²</h2>
             <div class="text-primary" style="font-size: 4rem;font-weight: bold;">{{ property.formattedPrice }} FCFA</div>
             <a href="#" class="btn btn-primary">Contacter l'agence</a>
             <div id="contactForm" class="mt-4">
                 {{ form_start(form) }}
                   <div class="row">
                       <div class="col">{{ form_row(form.firstname) }}</div>
                       <div class="col">{{ form_row(form.lastname) }}</div>
                   </div>
                 <div class="row">
                     <div class="col">{{ form_row(form.phone) }}</div>
                     <div class="col">{{ form_row(form.email) }}</div>
                 </div>
                 {{ form_rest(form) }}
                 <div class="form-group">
                     <button class="btn btn-primary">Envoyer</button>
                 </div>
                 {{ form_end(form) }}
             </div>
         </div>
     </div>
 <p>
     {{ property.description | nl2br }}
 </p>

     <div class="row">
         <div class="col-md-8">
             <h2>Caractéristiques</h2>
            <table class="table table-striped">
                <tr>
                    <td>Surface habitable</td>
                    <td>{{ property.surface }} m²</td>
                </tr>
                <tr>
                    <td>Pièces</td>
                    <td>{{ property.rooms }}</td>
                </tr>
                <tr>
                    <td>Chambres</td>
                    <td>{{ property.bedrooms }}</td>
                </tr>
                <tr>
                    <td>Etage</td>
                    <td>{{ property.floor }}</td>
                </tr>
                <tr>
                    <td>Chauffage</td>
                    <td>{{ property.heatType }}</td>
                </tr>
            </table>
         </div>
         <div class="col-md-4">
            <h2>Spécificités</h2>
             <ul class="list-group">
                 {% for option in property.options %}
                    <li class="list-group-item">{{ option.name }}</li>
                 {% endfor  %}
             </ul>

         </div>
     </div>
 </div>
{% endblock %}